---
name: Bug
description: Report a new bug
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Please describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Please list the exact steps necessary to reproduce the bug
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating system
    validations:
      required: true

  - type: input
    id: ivm-version
    attributes:
      label: ivm version
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust version
    validations:
      required: true
