---
name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_HOME: ${{ github.workspace }}/.cargo

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1

  # Clippy uses a specific version as its lints change over time, which could
  # result in random unrelated CI failures. We'll bump this version every now
  # and then when needed.
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.68
        with:
          components: 'clippy'
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cargo
            target
          key: ${{ runner.os }}-alpine
      - run: 'cargo clippy -- -D warnings'

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: 'rustfmt'
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cargo
            target
          key: ${{ runner.os }}-alpine
      - run: 'cargo fmt --all --check'

  gitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - run: pip install gitlint
      - run: git config --global --add safe.directory $PWD
      - run: gitlint --commits "HEAD~9..HEAD"

  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        version:
          - '1.68'
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.cargo
            target
          key: ${{ runner.os }}-stable
      - name: Running tests
        run: cargo test
